### ISSUE TITLE
Error trying to implement a redis store

### ISSUE THREAD

**Issue by clakech** [honeinc/woden#12]
Hi,

I am trying to create a redis implementation for the cache storage and I face a problem.

Since the redis client use async callback to work, then I got some problem when woden try to proxy.web the request. I get a socket hanging problem after a timeout...

Code of the redis storage for woden:
```
module.exports = {
    get: function (key, callback) {
        console.log("get key", key);
        client.get(key, function (err, reply) {
            console.log("get err", err);
            console.log("get reply", reply);
            callback(err, reply);
        });
    },
    set: function (options, callback) {
        console.log("set key", options.key);
        console.log("set value", options.value);
        client.set(options.key, options.value, redis.print);
        callback();
    }
};
```

error just in the self.proxy.web( req, res,...) code in woden:
``` 
error { [Error: socket hang up] code: 'ECONNRESET' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at createHangUpError (http.js:1477:15)
    at Socket.socketCloseListener (http.js:1527:23)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:466:12)
```

any idea ?

**Comment by jcblw** [comment]
hmmm i'm assuming this is happening a a get from cache or on the set?

**Comment by clakech** [comment]
The get from the cache works but after when we call the resource with
proxy.web the process hangs and I get a exception after a while.

Seems like there is a LOT of error using http-proxy that cause application
to hang.

Le vendredi 17 juillet 2015, Jacob Lowe <notifications@github.com> a écrit :

> hmmm i'm assuming this is happening a a get from cache or on the set?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/honeinc/woden/issues/12#issuecomment-122302213>.
>


-- 

Cyril Lakech

-- 
Ce message et toutes les pièces jointes sont établis à l'attention 
exclusive de leurs destinataires et sont confidentiels. Si vous recevez ce 
message par erreur, merci de le détruire et d'en avertir immédiatement 
l'expéditeur. L'internet ne permettant pas d'assurer l'intégrité de ce 
message, le contenu de ce message ne représente en aucun cas un engagement 
de la part de GROUPE ADEO.
